filter:
    paths: [src/*]
checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
            -
                command: 'composer test-coverage'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
